### ISSUE TITLE
Add command line support

### ISSUE THREAD

**Issue by aeilot** [BOOK-BLOG/tooltiplery.js#1]
It is a wonderful product and I truly love it. It will change the way we code.
I hope your next step will be:
Make it just like vuejs
And start an org called tooltiplery
I hope it will be like:
```bash
tpc init
tpc server
tpc deploy
tpc install
# ... etc.
```

**Comment by aeilot** [comment]
Add a tool called ```tooltiplery compiler for cli --> tpc```

**Comment by aeilot** [comment]
Hope you guys will make it like React or whatever and good luck!

**Comment by MrWillCom** [comment]
@aeilot tooltiplery.js is not a command tool. It's just like a plugin for your web site. It cannot create a whole web site, but part of it.
